// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htqtqkdzubporhfazoio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0cXRxa2R6dWJwb3JoZmF6b2lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMDMxMTYsImV4cCI6MjA1Nzg3OTExNn0.vZpS1aD13YeIegvNoYlczw4xAgJNbbEOfC3O3tGlZnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);